import type { Metadata } from "next";
import MarketingShell from "@/components/MarketingShell";
import Reveal from "@/components/Reveal";
import { FinalCta, PageHero, PrimaryCta } from "@/components/V2Ui";

export const metadata: Metadata = { title: "FAQ | Trayfolio", description: "Answers about working with Trayfolio, custom website scope, the $50 demo, launch, ownership, and support.", alternates: { canonical: "/faq" } };
const groups = [
  { title: "Getting started", items: [["Who does Trayfolio work with?", "Trayfolio works with small businesses across the United States that need a first professional website, a redesign, or a stronger digital experience."], ["Can you redesign a website I already have?", "Yes. A redesign can improve the visual direction, mobile experience, clarity, performance, and customer path while preserving what still works."], ["What if I am not sure what I need?", "That is exactly what the free 15-minute call is for. Start with the business goal; Trayfolio can help define the right website scope from there."]] },
  { title: "Scope, timing & pricing", items: [["How much does a website cost?", "Every project is scoped around the business, required functionality, content, and timeline. After a short discovery conversation, Trayfolio recommends a scope and provides clear project pricing before work begins."], ["How long does a project take?", "Timing depends on scope, content readiness, and feedback. The project timeline is discussed during discovery and confirmed with the project scope."], ["How do revisions work?", "Review points and revision expectations are defined in the project scope so both sides know how feedback and changes will be handled."]] },
  { title: "The $50 demo", items: [["What is the $50 website demo?", "It is a custom demonstration of a possible website direction for your actual business, delivered as a live link. It is not a complete website or project deposit."], ["When will it arrive?", "Within 48 hours after Trayfolio receives the business information needed to create it."], ["How does the credit work?", "If you move forward with a full website project, the $50 is credited toward that project according to the demo terms."], ["Is the demo refundable?", "The demo fee is non-refundable because it pays for custom work created for the business."]] },
  { title: "Launch & support", items: [["Do I own my website?", "Yes. Ownership, third-party licenses, and any ongoing service details are documented in the project agreement."], ["Can Trayfolio help after launch?", "Yes. Ongoing care and support can be included when the business needs continued help after launch."], ["Can you work with my existing domain or tools?", "Usually. Existing domains, booking tools, payment systems, and other integrations are reviewed during discovery so the project can account for them."]] },
];
export default function FaqPage() { return <MarketingShell><PageHero eyebrow="Frequently asked questions" title="The details before we begin." intro="Straight answers about scope, timing, the $50 demo, and what happens after launch."><PrimaryCta /></PageHero><section className="py-20 sm:py-28"><div className="v2-container max-w-4xl space-y-16">{groups.map((group, index) => <Reveal key={group.title} delay={index * 50}><h2 className="font-display text-3xl tracking-tight">{group.title}</h2><dl className="mt-6 divide-y divide-stone-200 border-y border-stone-200">{group.items.map(([question, answer]) => <div key={question} className="py-7"><dt className="font-display text-xl">{question}</dt><dd className="mt-3 leading-7 text-stone-600">{answer}</dd></div>)}</dl></Reveal>)}</div></section><FinalCta /></MarketingShell>; }
