import type { Metadata } from "next";
import { Check } from "lucide-react";
import MarketingShell from "@/components/MarketingShell";
import Reveal from "@/components/Reveal";
import { FinalCta, PageHero, PrimaryCta } from "@/components/V2Ui";

export const metadata: Metadata = { title: "About | Trayfolio", description: "Meet Trayfolio, a web design and development studio helping small businesses build a stronger place online.", alternates: { canonical: "/about" } };
const principles = ["Clear communication", "Thoughtful custom work", "Mobile-first decisions", "Honest scope and expectations", "One point of contact"];
export default function AboutPage() { return <MarketingShell><PageHero eyebrow="About Trayfolio" title="A small studio with a direct way of working." intro="Trayfolio helps small businesses get websites that feel considered, credible, and specific to what they do—not recycled from somebody else's business."><PrimaryCta /></PageHero><section className="py-20 sm:py-28"><div className="v2-container grid gap-12 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><Reveal><div className="grid aspect-square max-w-md place-items-center rounded-[2.5rem] bg-stone-950 text-white shadow-2xl"><span className="font-display text-[clamp(6rem,16vw,11rem)] tracking-[-.08em]">TH</span></div></Reveal><Reveal delay={100}><p className="v2-eyebrow text-stone-500">The person behind the studio</p><h2 className="v2-section-title mt-4">Work directly with the person designing and building your site.</h2><p className="mt-6 text-lg leading-8 text-stone-600">Trayfolio was founded by Tracy Holbrook to give small businesses a more thoughtful and straightforward website process. There are no layers of account handoffs: the conversation, design thinking, and development stay connected from first idea through launch.</p><p className="mt-5 text-lg leading-8 text-stone-600">The result is a process that can stay personal while the work remains focused on the Trayfolio brand and the business it is serving.</p></Reveal></div></section><section className="paper-texture py-20 sm:py-28"><div className="v2-container grid gap-12 lg:grid-cols-2"><Reveal><p className="v2-eyebrow text-stone-500">Studio principles</p><h2 className="v2-section-title mt-4">Professional does not have to mean impersonal.</h2></Reveal><Reveal delay={100}><ul className="grid gap-4">{principles.map((item) => <li key={item} className="flex items-center gap-3 border-b border-stone-900/10 pb-4 text-lg"><Check className="text-terracotta" size={18} aria-hidden="true" />{item}</li>)}</ul></Reveal></div></section><section className="bg-white py-20 sm:py-28"><div className="v2-container max-w-4xl text-center"><Reveal><p className="v2-eyebrow text-stone-500">Nationwide, still personal</p><h2 className="v2-section-title mt-4">Built for small businesses wherever the work takes place.</h2><p className="mx-auto mt-6 max-w-2xl text-lg leading-8 text-stone-600">Trayfolio works remotely with small businesses across the United States. Calls, reviews, and project decisions stay clear without requiring everyone to be in the same city.</p></Reveal></div></section><FinalCta /></MarketingShell>; }
