import type { Metadata } from "next";
import { Check } from "lucide-react";
import MarketingShell from "@/components/MarketingShell";
import Reveal from "@/components/Reveal";
import { FinalCta, PageHero, PrimaryCta, SecondaryCta } from "@/components/V2Ui";

export const metadata: Metadata = { title: "Services | Trayfolio", description: "Custom website design, development, redesigns, integrations, and support for small businesses.", alternates: { canonical: "/services" } };
const services = [["Custom websites", "Strategy, design, and development shaped around your business, customers, and goals."], ["Website redesigns", "A clearer, faster, more credible experience for a site that no longer represents the business."], ["Commerce & integrations", "Payments, stores, booking, lead capture, and other tools when they support the project."], ["Care & support", "Ongoing website help after launch, scoped around what the business actually needs."]];
const foundations = ["Intentional mobile experience", "Clear customer journeys", "Performance and accessibility", "Search and sharing foundations", "Launch planning and support"];

export default function ServicesPage() { return <MarketingShell><PageHero eyebrow="Services" title="Websites shaped around what your business needs next." intro="Every business has a different audience, offer, and way of working. Trayfolio defines the right scope through conversation instead of forcing the project into a public package."><PrimaryCta /><SecondaryCta /></PageHero><section className="py-20 sm:py-28"><div className="v2-container"><Reveal><p className="v2-eyebrow text-stone-500">What Trayfolio does</p><h2 className="v2-section-title mt-4">From first professional site to a complete rethink.</h2></Reveal><div className="mt-12 grid gap-5 sm:grid-cols-2">{services.map(([title, body], index) => <Reveal key={title} delay={(index % 2) * 70}><article className="h-full rounded-3xl border border-stone-200 bg-white p-7 sm:p-9"><span className="text-sm font-semibold text-terracotta">0{index + 1}</span><h3 className="font-display mt-6 text-3xl tracking-tight">{title}</h3><p className="mt-4 leading-7 text-stone-600">{body}</p></article></Reveal>)}</div></div></section><section className="paper-texture py-20 sm:py-28"><div className="v2-container grid gap-12 lg:grid-cols-2"><Reveal><p className="v2-eyebrow text-stone-500">Every project considers</p><h2 className="v2-section-title mt-4">The details that make a website feel trustworthy.</h2></Reveal><Reveal delay={100}><ul className="grid gap-4">{foundations.map((item) => <li key={item} className="flex items-center gap-3 border-b border-stone-900/10 pb-4 text-lg"><Check className="text-terracotta" size={19} aria-hidden="true" />{item}</li>)}</ul></Reveal></div></section><section className="bg-white py-20 sm:py-28"><div className="v2-container grid gap-10 lg:grid-cols-[1.2fr_.8fr] lg:items-center"><Reveal><p className="v2-eyebrow text-stone-500">How scope works</p><h2 className="v2-section-title mt-4">The right project starts with the right questions.</h2><p className="mt-6 max-w-2xl text-lg leading-8 text-stone-600">A free 15-minute call gives Trayfolio enough context to recommend a scope, timeline, and investment. You receive clear next steps before any full project begins.</p></Reveal><Reveal delay={100}><div className="rounded-3xl bg-stone-950 p-8 text-white"><p className="font-display text-2xl tracking-tight">A good fit if…</p><ul className="mt-6 space-y-4 text-sm leading-6 text-stone-300"><li>You need a first professional website.</li><li>Your current site no longer reflects the business.</li><li>Your mobile or customer journey feels unclear.</li><li>You need a stronger way to capture leads, bookings, or sales.</li></ul><PrimaryCta className="mt-7" /></div></Reveal></div></section><FinalCta /></MarketingShell>; }
